import Head from "next/head"

import "../css/globals.css"

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="shortcut icon" href="images/favicon.png" />
			</Head>

			<Component {...pageProps} />
		</>
	)
}

export default MyApp
